name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: lint
        uses: reviewdog/action-golangci-lint@v2.6.2
  test:
    env:
      TEST_TARGET: ./... github.com/aereal/otelgqlgen/test
    strategy:
      matrix:
        go_version:
          - stable
          - oldstable
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
          cache-dependency-path: |
            go.sum
            test/go.sum
      - run: |
          go work init ./ ./test
          go work sync
      - run: go mod download
      - name: test
        run: go test -v -race -coverprofile=cover.out $TEST_TARGET
      - uses: k1LoW/octocov-action@v1.3.0
        if: ${{ matrix.go_version == 'stable' }}
