name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  ok:
    if: failure()
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
      - check-code-generation
    steps:
      - run: exit 1
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - name: lint
        uses: reviewdog/action-golangci-lint@v2.6.2
  test:
    strategy:
      matrix:
        go_version:
          - stable
          - oldstable
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: ${{ matrix.go_version }}
          cache: true
          cache-dependency-path: |
            go.sum
      - run: go mod download
      - name: test
        run: go test -v -race -coverprofile=cover.out ./...
      - uses: k1LoW/octocov-action@v1.3.0
        if: ${{ matrix.go_version == 'stable' }}
  check-code-generation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-go@v5.1.0
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            go.sum
      - run: go mod download
      - run: go generate ./...
      - run: git diff --exit-code
